package main

var HeavyWeaponCatalog = []WeaponCatalogEntry{
	{
		ID:               "mag-7",
		Slot:             "heavy",
		Category:         "shotgun",
		Side:             "ct",
		Label:            "MAG-7",
		Price:            1300,
		KillReward:       900,
		MagSize:          5,
		ReserveMax:       32,
		ReloadMS:         2400,
		FireIntervalMS:   845,
		BaseDamage:       30,
		ArmorPenetration: 0.75,
		RangeModifier:    0.45,
		MoveSpeed:        225,
		ScopedMoveSpeed:  0,
		Pellets:          8,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "shotgun",
	},
	{
		ID:               "nova",
		Slot:             "heavy",
		Category:         "shotgun",
		Side:             "both",
		Label:            "Nova",
		Price:            1050,
		KillReward:       900,
		MagSize:          8,
		ReserveMax:       32,
		ReloadMS:         3400,
		FireIntervalMS:   882,
		BaseDamage:       26,
		ArmorPenetration: 0.5,
		RangeModifier:    0.7,
		MoveSpeed:        220,
		ScopedMoveSpeed:  0,
		Pellets:          9,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "shotgun",
	},
	{
		ID:               "sawed-off",
		Slot:             "heavy",
		Category:         "shotgun",
		Side:             "t",
		Label:            "Sawed-Off",
		Price:            1100,
		KillReward:       900,
		MagSize:          7,
		ReserveMax:       32,
		ReloadMS:         2800,
		FireIntervalMS:   845,
		BaseDamage:       32,
		ArmorPenetration: 0.75,
		RangeModifier:    0.45,
		MoveSpeed:        210,
		ScopedMoveSpeed:  0,
		Pellets:          8,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "shotgun",
	},
	{
		ID:               "xm1014",
		Slot:             "heavy",
		Category:         "shotgun",
		Side:             "both",
		Label:            "XM1014",
		Price:            2000,
		KillReward:       900,
		MagSize:          7,
		ReserveMax:       32,
		ReloadMS:         2760,
		FireIntervalMS:   350,
		BaseDamage:       20,
		ArmorPenetration: 0.8,
		RangeModifier:    0.7,
		MoveSpeed:        215,
		ScopedMoveSpeed:  0,
		Pellets:          6,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "shotgun",
	},
	{
		ID:               "m249",
		Slot:             "heavy",
		Category:         "machinegun",
		Side:             "both",
		Label:            "M249",
		Price:            5200,
		KillReward:       300,
		MagSize:          100,
		ReserveMax:       200,
		ReloadMS:         5700,
		FireIntervalMS:   80,
		BaseDamage:       32,
		ArmorPenetration: 0.8,
		RangeModifier:    0.97,
		MoveSpeed:        195,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "lmg",
	},
	{
		ID:               "negev",
		Slot:             "heavy",
		Category:         "machinegun",
		Side:             "both",
		Label:            "Negev",
		Price:            1700,
		KillReward:       300,
		MagSize:          150,
		ReserveMax:       300,
		ReloadMS:         5700,
		FireIntervalMS:   75,
		BaseDamage:       35,
		ArmorPenetration: 0.71,
		RangeModifier:    0.97,
		MoveSpeed:        150,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "lmg",
	},
}
