package main

var PistolWeaponCatalog = []WeaponCatalogEntry{
	{
		ID:               "cz75-auto",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "both",
		Label:            "CZ75-Auto",
		Price:            500,
		KillReward:       100,
		MagSize:          12,
		ReserveMax:       12,
		ReloadMS:         2800,
		FireIntervalMS:   100,
		BaseDamage:       31,
		ArmorPenetration: 0.777,
		RangeModifier:    0.85,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "auto",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "desert-eagle",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "both",
		Label:            "Desert Eagle",
		Price:            700,
		KillReward:       300,
		MagSize:          7,
		ReserveMax:       35,
		ReloadMS:         2200,
		FireIntervalMS:   225,
		BaseDamage:       53,
		ArmorPenetration: 0.932,
		RangeModifier:    0.81,
		MoveSpeed:        230,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "dual-berettas",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "both",
		Label:            "Dual Berettas",
		Price:            300,
		KillReward:       300,
		MagSize:          30,
		ReserveMax:       120,
		ReloadMS:         3770,
		FireIntervalMS:   120,
		BaseDamage:       38,
		ArmorPenetration: 0.575,
		RangeModifier:    0.81,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "five-seven",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "ct",
		Label:            "Five-SeveN",
		Price:            500,
		KillReward:       300,
		MagSize:          20,
		ReserveMax:       100,
		ReloadMS:         2200,
		FireIntervalMS:   150,
		BaseDamage:       32,
		ArmorPenetration: 0.9115,
		RangeModifier:    0.885,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "glock-18",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "t",
		Label:            "Glock-18",
		Price:            200,
		KillReward:       300,
		MagSize:          20,
		ReserveMax:       120,
		ReloadMS:         2200,
		FireIntervalMS:   150,
		BaseDamage:       30,
		ArmorPenetration: 0.47,
		RangeModifier:    0.85,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "burst",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "p2000",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "ct",
		Label:            "P2000",
		Price:            200,
		KillReward:       300,
		MagSize:          13,
		ReserveMax:       52,
		ReloadMS:         2200,
		FireIntervalMS:   170,
		BaseDamage:       35,
		ArmorPenetration: 0.505,
		RangeModifier:    0.91,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "p250",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "both",
		Label:            "P250",
		Price:            300,
		KillReward:       300,
		MagSize:          13,
		ReserveMax:       26,
		ReloadMS:         2200,
		FireIntervalMS:   150,
		BaseDamage:       38,
		ArmorPenetration: 0.64,
		RangeModifier:    0.90,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "r8-revolver",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "both",
		Label:            "R8 Revolver",
		Price:            600,
		KillReward:       300,
		MagSize:          8,
		ReserveMax:       8,
		ReloadMS:         2300,
		FireIntervalMS:   706,
		BaseDamage:       86,
		ArmorPenetration: 0.932,
		RangeModifier:    0.98,
		MoveSpeed:        220,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "revolver",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "tec-9",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "t",
		Label:            "Tec-9",
		Price:            500,
		KillReward:       300,
		MagSize:          18,
		ReserveMax:       90,
		ReloadMS:         2500,
		FireIntervalMS:   120,
		BaseDamage:       33,
		ArmorPenetration: 0.902,
		RangeModifier:    0.79,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
	{
		ID:               "usp-s",
		Slot:             "pistol",
		Category:         "pistol",
		Side:             "ct",
		Label:            "USP-S",
		Price:            200,
		KillReward:       300,
		MagSize:          12,
		ReserveMax:       24,
		ReloadMS:         2200,
		FireIntervalMS:   170,
		BaseDamage:       35,
		ArmorPenetration: 0.505,
		RangeModifier:    0.91,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "silencer",
		ZoomLevels:       []float64{},
		RenderClass:      "pistol",
	},
}
