package main

var SMGWeaponCatalog = []WeaponCatalogEntry{
	{
		ID:               "mac10",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "t",
		Label:            "MAC-10",
		Price:            1050,
		KillReward:       600,
		MagSize:          30,
		ReserveMax:       100,
		ReloadMS:         2600,
		FireIntervalMS:   75,
		BaseDamage:       29,
		ArmorPenetration: 0.575,
		RangeModifier:    0.8,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "mp5-sd",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "both",
		Label:            "MP5-SD",
		Price:            1500,
		KillReward:       600,
		MagSize:          30,
		ReserveMax:       120,
		ReloadMS:         3000,
		FireIntervalMS:   80,
		BaseDamage:       28,
		ArmorPenetration: 0.625,
		RangeModifier:    0.87,
		MoveSpeed:        235,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "mp7",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "both",
		Label:            "MP7",
		Price:            1500,
		KillReward:       600,
		MagSize:          30,
		ReserveMax:       120,
		ReloadMS:         3100,
		FireIntervalMS:   80,
		BaseDamage:       29,
		ArmorPenetration: 0.625,
		RangeModifier:    0.85,
		MoveSpeed:        220,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "mp9",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "ct",
		Label:            "MP9",
		Price:            1250,
		KillReward:       600,
		MagSize:          30,
		ReserveMax:       120,
		ReloadMS:         2100,
		FireIntervalMS:   70,
		BaseDamage:       26,
		ArmorPenetration: 0.6,
		RangeModifier:    0.87,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "pp-bizon",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "both",
		Label:            "PP-Bizon",
		Price:            1400,
		KillReward:       600,
		MagSize:          64,
		ReserveMax:       120,
		ReloadMS:         2400,
		FireIntervalMS:   80,
		BaseDamage:       27,
		ArmorPenetration: 0.64,
		RangeModifier:    0.8,
		MoveSpeed:        240,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "p90",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "both",
		Label:            "P90",
		Price:            2350,
		KillReward:       300,
		MagSize:          50,
		ReserveMax:       100,
		ReloadMS:         3300,
		FireIntervalMS:   70,
		BaseDamage:       26,
		ArmorPenetration: 0.69,
		RangeModifier:    0.84,
		MoveSpeed:        230,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
	{
		ID:               "ump-45",
		Slot:             "heavy",
		Category:         "smg",
		Side:             "both",
		Label:            "UMP-45",
		Price:            1200,
		KillReward:       600,
		MagSize:          25,
		ReserveMax:       100,
		ReloadMS:         3500,
		FireIntervalMS:   100,
		BaseDamage:       35,
		ArmorPenetration: 0.65,
		RangeModifier:    0.75,
		MoveSpeed:        230,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "smg",
	},
}
