package main

var RifleWeaponCatalog = []WeaponCatalogEntry{
	{
		ID:               "ak-47",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "t",
		Label:            "AK-47",
		Price:            2700,
		KillReward:       300,
		MagSize:          30,
		ReserveMax:       90,
		ReloadMS:         2400,
		FireIntervalMS:   100,
		BaseDamage:       35,
		ArmorPenetration: 0.775,
		RangeModifier:    0.98,
		MoveSpeed:        215,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "rifle",
	},
	{
		ID:               "aug",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "ct",
		Label:            "AUG",
		Price:            3300,
		KillReward:       300,
		MagSize:          30,
		ReserveMax:       90,
		ReloadMS:         3300,
		FireIntervalMS:   100,
		BaseDamage:       28,
		ArmorPenetration: 0.9,
		RangeModifier:    0.96,
		MoveSpeed:        220,
		ScopedMoveSpeed:  150,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.85},
		RenderClass:      "rifle",
	},
	{
		ID:               "awp",
		Slot:             "heavy",
		Category:         "sniper",
		Side:             "both",
		Label:            "AWP",
		Price:            4750,
		KillReward:       100,
		MagSize:          5,
		ReserveMax:       30,
		ReloadMS:         3700,
		FireIntervalMS:   1463,
		BaseDamage:       115,
		ArmorPenetration: 0.97,
		RangeModifier:    0.99,
		MoveSpeed:        200,
		ScopedMoveSpeed:  100,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.55},
		RenderClass:      "sniper",
	},
	{
		ID:               "famas",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "ct",
		Label:            "FAMAS",
		Price:            2050,
		KillReward:       300,
		MagSize:          25,
		ReserveMax:       90,
		ReloadMS:         3300,
		FireIntervalMS:   90,
		BaseDamage:       30,
		ArmorPenetration: 0.7,
		RangeModifier:    0.96,
		MoveSpeed:        220,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "burst",
		ZoomLevels:       []float64{},
		RenderClass:      "rifle",
	},
	{
		ID:               "g3sg1",
		Slot:             "heavy",
		Category:         "sniper",
		Side:             "t",
		Label:            "G3SG1",
		Price:            5000,
		KillReward:       100,
		MagSize:          20,
		ReserveMax:       90,
		ReloadMS:         4700,
		FireIntervalMS:   250,
		BaseDamage:       80,
		ArmorPenetration: 0.825,
		RangeModifier:    0.98,
		MoveSpeed:        215,
		ScopedMoveSpeed:  120,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.55},
		RenderClass:      "sniper",
	},
	{
		ID:               "galil-ar",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "t",
		Label:            "Galil AR",
		Price:            1800,
		KillReward:       300,
		MagSize:          35,
		ReserveMax:       90,
		ReloadMS:         3000,
		FireIntervalMS:   90,
		BaseDamage:       30,
		ArmorPenetration: 0.775,
		RangeModifier:    0.98,
		MoveSpeed:        215,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "rifle",
	},
	{
		ID:               "m4a1-s",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "ct",
		Label:            "M4A1-S",
		Price:            2900,
		KillReward:       300,
		MagSize:          20,
		ReserveMax:       80,
		ReloadMS:         3100,
		FireIntervalMS:   100,
		BaseDamage:       38,
		ArmorPenetration: 0.7,
		RangeModifier:    0.94,
		MoveSpeed:        225,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "silencer",
		ZoomLevels:       []float64{},
		RenderClass:      "rifle",
	},
	{
		ID:               "m4a4",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "ct",
		Label:            "M4A4",
		Price:            3100,
		KillReward:       300,
		MagSize:          30,
		ReserveMax:       90,
		ReloadMS:         3100,
		FireIntervalMS:   90,
		BaseDamage:       33,
		ArmorPenetration: 0.7,
		RangeModifier:    0.97,
		MoveSpeed:        225,
		ScopedMoveSpeed:  0,
		Pellets:          1,
		SecondaryMode:    "none",
		ZoomLevels:       []float64{},
		RenderClass:      "rifle",
	},
	{
		ID:               "scar-20",
		Slot:             "heavy",
		Category:         "sniper",
		Side:             "ct",
		Label:            "SCAR-20",
		Price:            5000,
		KillReward:       100,
		MagSize:          20,
		ReserveMax:       90,
		ReloadMS:         3100,
		FireIntervalMS:   250,
		BaseDamage:       80,
		ArmorPenetration: 0.825,
		RangeModifier:    0.98,
		MoveSpeed:        215,
		ScopedMoveSpeed:  120,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.55},
		RenderClass:      "sniper",
	},
	{
		ID:               "sg553",
		Slot:             "heavy",
		Category:         "rifle",
		Side:             "t",
		Label:            "SG 553",
		Price:            3000,
		KillReward:       300,
		MagSize:          30,
		ReserveMax:       90,
		ReloadMS:         2800,
		FireIntervalMS:   110,
		BaseDamage:       30,
		ArmorPenetration: 1.0,
		RangeModifier:    0.98,
		MoveSpeed:        210,
		ScopedMoveSpeed:  150,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.85},
		RenderClass:      "rifle",
	},
	{
		ID:               "ssg08",
		Slot:             "heavy",
		Category:         "sniper",
		Side:             "both",
		Label:            "SSG 08",
		Price:            1700,
		KillReward:       300,
		MagSize:          10,
		ReserveMax:       90,
		ReloadMS:         3700,
		FireIntervalMS:   1250,
		BaseDamage:       88,
		ArmorPenetration: 0.85,
		RangeModifier:    0.98,
		MoveSpeed:        230,
		ScopedMoveSpeed:  150,
		Pellets:          1,
		SecondaryMode:    "scope",
		ZoomLevels:       []float64{0.55},
		RenderClass:      "sniper",
	},
}
